variables:
  DOCKER_FILE: 'WetPicsRebirth\Dockerfile'

stages:
  - build

build_job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    - master  # the build process will only be started by git tag commits
  before_script:
    - docker info
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker build --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" --tag "$CI_REGISTRY_IMAGE:latest" ./WetPicsRebirth/Dockerfile
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  tags:
  - docker
