name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.5.0'
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run GitVersion
        id:   gitversion
        uses: GitTools/actions/gitversion/execute@v0.9.11

      - name: Echo version 
        run: echo ${{ steps.gitversion.outputs.majorMinorPatch }}
        
      - name: Build
        run: |
          ls
          cd ../Source
          docker build --tag=imoutochan/wetpicsrebirth:${{ steps.gitversion.outputs.majorMinorPatch }} -t imoutochan/wetpicsrebirth . -f WetPicsRebirth/Dockerfile
          docker push imoutochan/wetpicsrebirth:${{ steps.gitversion.outputs.majorMinorPatch }}
          docker push imoutochan/wetpicsrebirth:latest
