name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.5.0'
      
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run GitVersion
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0
        env:
          DOTNET_ROLL_FORWARD: Major

      - name: Echo version 
        run: echo ${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          context: ./Source
          file: ./Source/WetPicsRebirth/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/wetpicsrebirth:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/wetpicsrebirth:${{ steps.gitversion.outputs.majorMinorPatch }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/wetpicsrebirth:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/wetpicsrebirth:buildcache,mode=max
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: ./update.wetpicsrebirthbot.sh
